import type { LexiconEntry } from "./types.js";

/**
 * 병동 은어 확장분 — 실제로 입에서 나오는 말들.
 *
 * `abbreviations.ts`가 "기록에 적히는 약어"를 담는다면, 여기는 **소리로만 오가는 말**이다.
 * 인계에서 "새츄 떨어져요", "컨디션 다운이에요", "라인 터졌어요" 라고 하지
 * "산소포화도가 저하되었습니다" 라고 하지 않는다. 신규가 못 알아듣는 건 대부분 이쪽이다.
 *
 * 외래어를 한글로 적은 것이 많은데, 이게 전사에서 특히 중요하다.
 * 음성인식은 이런 말을 소리대로 적을 수밖에 없고(원래 그렇게 발음하니까),
 * 사전에 없으면 통째로 엉뚱한 단어가 된다.
 *
 * 은어와 기록 표현을 쌍으로 둔 이유는 `slang.ts` 머리말에 적어 두었다 —
 * 대화에서는 통해도 간호기록에 그대로 쓰면 법적 문서로서 결함이 된다.
 */
export const SLANG_EXTRA_TERMS: LexiconEntry[] = [
  // ── 환자 상태를 말할 때 ──────────────────────────────────
  {
    id: "condition-down",
    ko: "상태 악화",
    en: "condition down",
    aliases: ["컨디션다운", "컨디션 다운", "컨디션떨어짐", "상태 다운"],
    category: "condition",
    definition: "환자 상태가 전반적으로 나빠진 것을 뭉뚱그려 부르는 말.",
    informal: true,
    formal: "전신 상태 악화",
    pitfall:
      "기록에 '컨디션 다운'이라고만 적으면 무엇이 어떻게 나빠졌는지 남지 않는다. 활력징후·의식·소변량 중 무엇이 어떻게 변했는지를 숫자로 적는다.",
  },
  {
    id: "desaturation",
    ko: "산소포화도 저하",
    en: "desaturation",
    aliases: ["데사트", "새츄 떨어짐", "사츄떨어짐", "디새추레이션", "포화도 저하"],
    category: "condition",
    definition: "산소포화도가 기준 아래로 떨어진 것.",
    informal: true,
    formal: "산소포화도 저하",
    pitfall: "떨어진 수치와 그때의 산소 투여량을 함께 적어야 의미가 있다. 90%가 실내공기에서인지 마스크 5L에서인지는 완전히 다른 상황이다.",
  },
  {
    id: "bradycardia-slang",
    ko: "서맥",
    en: "bradycardia",
    aliases: ["브래디", "브라디", "브래디카디아", "맥박 느림"],
    category: "condition",
    definition: "심박수가 정상보다 느린 상태. 성인 기준 분당 60회 미만.",
    informal: true,
    formal: "서맥",
  },
  {
    id: "tachycardia-slang",
    ko: "빈맥",
    en: "tachycardia",
    aliases: ["타키", "타키카디아", "맥박 빠름"],
    category: "condition",
    definition: "심박수가 정상보다 빠른 상태. 성인 기준 분당 100회 초과.",
    informal: true,
    formal: "빈맥",
  },
  {
    id: "apnea",
    ko: "무호흡",
    en: "apnea",
    aliases: ["아프네아", "앱니아", "무호흡"],
    category: "condition",
    definition: "호흡이 멈춘 상태.",
    informal: true,
    formal: "무호흡",
  },
  {
    id: "dyspnea",
    ko: "호흡곤란",
    en: "dyspnea",
    aliases: ["디스프네아", "디스프니아", "숨찬다", "숨차함"],
    category: "condition",
    definition: "숨쉬기 힘든 주관적 느낌.",
    informal: true,
    formal: "호흡곤란",
  },
  {
    id: "wheezing",
    ko: "천명음",
    en: "wheezing",
    aliases: ["휘징", "위징", "쌕쌕거림", "휘즈"],
    category: "condition",
    definition: "좁아진 기도를 지나는 공기가 내는 고음의 호흡음.",
    informal: true,
    formal: "천명음",
  },
  {
    id: "crackle",
    ko: "수포음",
    en: "crackle / rale",
    aliases: ["크래클", "랠", "라음", "거품소리"],
    category: "condition",
    definition: "폐포가 열릴 때 나는 자잘한 호흡음. 폐부종·폐렴에서 들린다.",
    informal: true,
    formal: "수포음",
  },
  {
    id: "gurgling",
    ko: "그르렁거림",
    en: "gurgling",
    aliases: ["가글링", "그르렁", "가래 끓음"],
    category: "condition",
    definition: "기도에 분비물이 고여 나는 소리. 흡인이 필요하다는 신호일 수 있다.",
    informal: true,
    formal: "기도 분비물 저류음",
  },
  {
    id: "sputum",
    ko: "객담",
    en: "sputum",
    aliases: ["스푸툼", "스퓨텀", "가래"],
    category: "condition",
    definition: "기도에서 나오는 분비물.",
    informal: true,
    formal: "객담",
    pitfall: "양·색·점도를 함께 적는다. '가래 많음'만으로는 다음 근무자가 비교할 수 없다.",
  },
  {
    id: "cyanosis",
    ko: "청색증",
    en: "cyanosis",
    aliases: ["치아노제", "시아노제", "사이아노시스", "입술 파래짐"],
    category: "condition",
    definition: "산소가 부족해 피부·점막이 푸르스름해지는 것.",
    informal: true,
    formal: "청색증",
  },
  {
    id: "edema-slang",
    ko: "부종",
    en: "edema",
    aliases: ["에데마", "이데마", "부었음", "붓기"],
    category: "condition",
    definition: "조직에 체액이 고여 붓는 것.",
    informal: true,
    formal: "부종",
    pitfall: "함요부종(pitting)인지, 어느 부위에 몇 도인지를 적는다. '다리 부음'만으로는 경과를 볼 수 없다.",
  },
  {
    id: "distension",
    ko: "복부 팽만",
    en: "abdominal distension",
    aliases: ["디스텐션", "복부 디스텐션", "배 빵빵함", "팽만"],
    category: "condition",
    definition: "복부가 부풀어 오른 상태.",
    informal: true,
    formal: "복부 팽만",
  },
  {
    id: "tenderness",
    ko: "압통",
    en: "tenderness",
    aliases: ["텐더니스", "누르면 아픔", "압통"],
    category: "condition",
    definition: "눌렀을 때 아픈 것.",
    informal: true,
    formal: "압통",
  },
  {
    id: "melena",
    ko: "흑색변",
    en: "melena",
    aliases: ["멜레나", "메레나", "검은변", "타르변"],
    category: "condition",
    definition: "상부위장관 출혈로 검고 끈적한 변이 나오는 것.",
    informal: true,
    formal: "흑색변",
    pitfall: "상부위장관 출혈 신호다. 발견 즉시 보고 대상이며 활력징후를 함께 확인한다.",
  },
  {
    id: "hematochezia",
    ko: "혈변",
    en: "hematochezia",
    aliases: ["헤마토케지아", "선혈변", "피변"],
    category: "condition",
    definition: "밝은 붉은색 피가 변에 섞여 나오는 것.",
    informal: true,
    formal: "혈변",
  },
  {
    id: "hematuria",
    ko: "혈뇨",
    en: "hematuria",
    aliases: ["헤마투리아", "피오줌", "붉은 소변"],
    category: "condition",
    definition: "소변에 피가 섞여 나오는 것.",
    informal: true,
    formal: "혈뇨",
  },
  {
    id: "oliguria",
    ko: "핍뇨",
    en: "oliguria",
    aliases: ["올리구리아", "소변 안 나옴", "소변량 감소"],
    category: "condition",
    definition: "소변량이 크게 줄어든 상태. 성인 기준 시간당 0.5mL/kg 미만.",
    informal: true,
    formal: "핍뇨",
    pitfall: "신기능 악화와 순환 부전의 초기 신호다. 시간당 소변량을 세어 보고한다.",
  },
  {
    id: "seizure-slang",
    ko: "경련",
    en: "seizure",
    aliases: ["시져", "시쥬어", "씨져", "경련발작", "발작"],
    category: "emergency",
    definition: "뇌의 비정상적 전기활동으로 생기는 발작.",
    informal: true,
    formal: "경련",
    pitfall: "억지로 붙잡거나 입에 무언가를 넣지 않는다. 시작 시각·지속 시간·양상을 보는 것이 처치만큼 중요하다.",
  },
  {
    id: "febrile",
    ko: "발열",
    en: "febrile",
    aliases: ["피버", "페브릴", "열난다", "열남"],
    category: "condition",
    definition: "체온이 정상보다 높은 상태.",
    informal: true,
    formal: "발열",
  },
  {
    id: "chill",
    ko: "오한",
    en: "chill",
    aliases: ["칠", "오한", "떨림", "쉬버링"],
    category: "condition",
    definition: "춥고 떨리는 느낌. 체온 상승 직전에 흔히 나타난다.",
    informal: true,
    formal: "오한",
    pitfall: "수혈·항생제 투여 중의 오한은 부작용 신호일 수 있다. 투여 중이면 일단 멈추고 확인한다.",
  },
  {
    id: "drowsy",
    ko: "기면",
    en: "drowsy",
    aliases: ["드로시", "드라우지", "졸림", "처짐"],
    category: "condition",
    definition: "자극을 주면 깨지만 금방 다시 잠드는 의식 수준.",
    informal: true,
    formal: "기면",
  },
  {
    id: "stupor",
    ko: "혼미",
    en: "stupor",
    aliases: ["스투퍼", "스투포", "혼미"],
    category: "condition",
    definition: "강한 자극에만 반응하는 의식 수준.",
    informal: true,
    formal: "혼미",
  },
  {
    id: "alert-status",
    ko: "명료",
    en: "alert",
    aliases: ["얼러트", "알러트", "명료", "의식 명료"],
    category: "condition",
    definition: "깨어 있고 지남력이 유지된 의식 수준.",
    informal: true,
    formal: "명료",
  },
  {
    id: "orientation",
    ko: "지남력",
    en: "orientation",
    aliases: ["오리엔테이션", "지남력", "오리엔"],
    category: "assessment",
    definition: "사람·장소·시간을 인식하는 능력.",
    informal: true,
    formal: "지남력",
    pitfall:
      "신규 교육의 '오리엔테이션'과 같은 말이라 문맥을 봐야 한다. 인계에서 '오리엔테이션 안 됩니다'는 환자의 지남력 이야기다.",
  },
  {
    id: "restless",
    ko: "안절부절못함",
    en: "restless",
    aliases: ["리스트리스", "안절부절", "가만히 못 있음"],
    category: "condition",
    definition: "가만히 있지 못하고 계속 움직이는 상태. 저산소증·통증·섬망의 신호일 수 있다.",
    informal: true,
    formal: "안절부절못함",
  },
  {
    id: "agitation",
    ko: "초조",
    en: "agitation",
    aliases: ["어지테이션", "아지테이션", "흥분", "난폭"],
    category: "condition",
    definition: "불안하고 흥분된 상태. 억제대를 고려하기 전에 원인을 먼저 찾는다.",
    informal: true,
    formal: "초조",
  },

  // ── 라인·수액·투약을 말할 때 ───────────────────────────
  {
    id: "flushing",
    ko: "관 세척",
    en: "flushing",
    aliases: ["플러싱", "플러쉬", "플러시", "라인 밀기"],
    category: "procedure",
    definition: "카테터 내강을 생리식염수 등으로 밀어 막힘과 약물 잔류를 막는 처치.",
    informal: true,
    formal: "카테터 세척",
    pitfall: "주사기 크기가 작을수록 압력이 세진다. 가는 관에 작은 주사기로 세게 밀면 관이 터진다.",
  },
  {
    id: "angio-catheter",
    ko: "정맥 유치침",
    en: "angiocatheter",
    aliases: ["앤지오", "안지오", "앤지오캇", "유치침", "카테터침"],
    category: "device",
    definition: "말초정맥에 넣어 두는 짧은 플라스틱 카테터.",
    informal: true,
    formal: "말초정맥 카테터",
  },
  {
    id: "butterfly-needle",
    ko: "나비침",
    en: "butterfly needle",
    aliases: ["버터플라이", "나비바늘", "나비침"],
    category: "device",
    definition: "양쪽에 날개가 달린 채혈·주사용 바늘.",
    informal: true,
    formal: "날개 달린 주사침",
  },
  {
    id: "metriset",
    ko: "정량 수액세트",
    en: "metriset / burette set",
    aliases: ["미터셋", "메트리셋", "뷰렛셋"],
    category: "device",
    definition: "정해진 양만 담아 떨어뜨리는 수액세트. 소아와 정밀 조절이 필요한 경우에 쓴다.",
    informal: true,
    formal: "정량 수액세트",
  },
  {
    id: "chamber",
    ko: "점적통",
    en: "drip chamber",
    aliases: ["챔버", "드립챔버", "점적통"],
    category: "device",
    definition: "수액이 방울로 떨어지는 것을 보는 투명한 통. 속도 조절의 기준점.",
    informal: true,
    formal: "점적통",
  },
  {
    id: "ampule",
    ko: "앰플",
    en: "ampule",
    aliases: ["앰플", "앰퓰", "암플"],
    category: "medication",
    definition: "한 번 쓰고 버리는 유리 밀봉 용기.",
    pitfall: "부러뜨린 뒤 유리 조각이 들어갈 수 있다. 필터 니들 사용 여부는 병원 지침을 따른다.",
  },
  {
    id: "vial",
    ko: "바이알",
    en: "vial",
    aliases: ["바이알", "바이엘", "병약"],
    category: "medication",
    definition: "고무 마개가 달린 약병. 여러 번 뽑아 쓸 수 있는 것과 아닌 것이 있다.",
    pitfall: "다회용 바이알은 개봉일과 유효기간을 적는다. 적지 않으면 언제 딴 것인지 아무도 모른다.",
  },
  {
    id: "skin-test",
    ko: "항생제 피부반응검사",
    en: "antibiotic skin test",
    aliases: ["에이에스티", "스킨테스트", "스킨테", "피부반응검사"],
    category: "medication",
    abbr: "AST",
    definition: "항생제 투여 전 과민반응 여부를 보는 피내 검사.",
    pitfall:
      "검사 자체로도 아나필락시스가 올 수 있다. 시행 후 자리를 뜨지 말고 관찰하며, 응급 약물 위치를 미리 확인한다.",
  },
  {
    id: "hartmann-solution",
    ko: "하트만 용액",
    en: "Hartmann's solution / lactated Ringer's",
    aliases: ["하트만", "하트만솔루션", "락테이트링거", "엘알"],
    category: "medication",
    definition: "전해질 조성이 세포외액에 가까운 수액. 수술·탈수에서 널리 쓴다.",
  },
  {
    id: "iv-full-open",
    ko: "최대 속도 주입",
    en: "full open",
    aliases: ["풀로 열다", "풀오픈", "풀로 달다", "풀드랍"],
    category: "medication",
    definition: "수액 조절기를 최대로 열어 빠르게 주입하는 것.",
    informal: true,
    formal: "최대 속도로 정맥 주입",
    pitfall: "심부전·신부전 환자에게는 폐부종을 만들 수 있다. 처방된 속도인지 반드시 확인한다.",
  },

  // ── 업무를 말할 때 ──────────────────────────────────────
  {
    id: "charting",
    ko: "간호기록 작성",
    en: "charting",
    aliases: ["챠팅", "차팅", "기록", "차트 쓰기"],
    category: "documentation",
    definition: "간호 행위와 관찰을 기록에 남기는 일.",
    informal: true,
    formal: "간호기록 작성",
    pitfall: "기록하지 않은 간호는 하지 않은 것으로 본다. 몰아서 쓰면 시각이 부정확해지고 그 자체가 결함이 된다.",
  },
  {
    id: "lab-out",
    ko: "검체 내보내기",
    en: "send labs",
    aliases: ["랩 나가다", "랩 나감", "검체 나감", "랩 보내기"],
    category: "workflow",
    definition: "채취한 검체를 검사실로 보내는 것.",
    informal: true,
    formal: "검체 검사실 이송",
    pitfall: "'랩 나갔다'와 '랩 나왔다'는 정반대다. 전자는 보냈다는 뜻, 후자는 결과가 왔다는 뜻이다.",
  },
  {
    id: "lab-result-in",
    ko: "검사 결과 확인",
    en: "labs are back",
    aliases: ["랩 나왔다", "결과 떴다", "결과 나옴", "랩 떴다"],
    category: "workflow",
    definition: "검사 결과가 나온 것.",
    informal: true,
    formal: "검사 결과 확인",
  },
  {
    id: "admission-slang",
    ko: "입원 접수",
    en: "admission",
    aliases: ["어드미", "어드미션", "뉴환자", "새 환자"],
    category: "workflow",
    definition: "새 환자가 병동에 입원하는 것, 또는 그 절차.",
    informal: true,
    formal: "입원",
    pitfall: "입원 시 전신 피부 상태를 기록해야 원내 발생 욕창인지 아닌지를 나중에 가릴 수 있다.",
  },
  {
    id: "nurse-station",
    ko: "간호사실",
    en: "nurses' station",
    aliases: ["스테이션", "널스스테이션", "간호사실", "데스크"],
    category: "workflow",
    definition: "병동의 업무 거점.",
    informal: true,
    formal: "간호사실",
  },
  {
    id: "nurse-call",
    ko: "호출벨",
    en: "nurse call",
    aliases: ["널스콜", "콜벨", "호출벨", "콜"],
    category: "device",
    definition: "환자가 간호사를 부르는 장치.",
    informal: true,
    formal: "환자 호출벨",
    pitfall: "손이 닿는 곳에 두었는지 확인하는 것이 낙상 예방의 기본이다. 침상을 떠날 때마다 확인한다.",
  },
  {
    id: "emergency-cart",
    ko: "응급카트",
    en: "crash cart",
    aliases: ["크래시카트", "이머전시카트", "응급카트", "응카"],
    category: "device",
    definition: "심정지 등 응급 상황에 쓰는 약물과 기구를 모아 둔 이동식 수레.",
    informal: true,
    formal: "응급카트",
    pitfall: "근무 시작 때 봉인과 제세동기 충전 상태를 확인한다. 정작 필요할 때 확인하면 늦다.",
  },
  {
    id: "intubation",
    ko: "기관삽관",
    en: "intubation",
    aliases: ["인투베이션", "인튜베이션", "인투", "삽관"],
    category: "procedure",
    definition: "기도에 관을 넣어 기도를 확보하는 처치.",
    informal: true,
    formal: "기관삽관",
  },
  {
    id: "extubation",
    ko: "발관",
    en: "extubation",
    aliases: ["익스투베이션", "발관", "튜브 뺌"],
    category: "procedure",
    definition: "기관내관을 제거하는 것.",
    informal: true,
    formal: "발관",
    pitfall: "발관 후 몇 시간이 가장 위험하다. 호흡음·목소리·산소포화도를 자주 확인한다.",
  },
  {
    id: "weaning",
    ko: "이탈 훈련",
    en: "weaning",
    aliases: ["위닝", "위닝중", "이탈"],
    category: "procedure",
    definition: "인공호흡기 등 보조에서 서서히 벗어나게 하는 과정.",
    informal: true,
    formal: "인공호흡기 이탈",
  },
  {
    id: "ambulation",
    ko: "보행",
    en: "ambulation",
    aliases: ["앰뷸레이션", "앰뷸", "보행", "걷기"],
    category: "procedure",
    definition: "환자를 걷게 하는 것. 수술 후 합병증 예방의 핵심 중재.",
    informal: true,
    formal: "보행",
    pitfall: "첫 보행은 반드시 동반한다. 기립성 저혈압으로 그 자리에서 쓰러지는 경우가 흔하다.",
  },
  {
    id: "total-care",
    ko: "전적 간호",
    en: "total care",
    aliases: ["토탈케어", "풀케어", "전적케어"],
    category: "workflow",
    definition: "환자가 스스로 하지 못해 모든 일상활동을 간호사가 제공하는 것.",
    informal: true,
    formal: "전적 간호",
  },
  {
    id: "self-care",
    ko: "자가 간호",
    en: "self-care",
    aliases: ["셀프케어", "셀프", "자가간호"],
    category: "workflow",
    definition: "환자가 스스로 일상활동을 수행하는 것.",
    informal: true,
    formal: "자가 간호",
  },
  {
    id: "side-rail",
    ko: "침상난간",
    en: "side rail",
    aliases: ["사이드레일", "침대난간", "레일"],
    category: "device",
    definition: "침대 양옆의 난간. 낙상 예방의 기본 조치.",
    informal: true,
    formal: "침상난간",
    pitfall: "난간을 올려도 넘어서 내려오다 더 크게 다치는 경우가 있다. 난간만으로 낙상을 막았다고 보면 안 된다.",
  },
  {
    id: "narcotic-stock",
    ko: "마약류 재고",
    en: "narcotic stock",
    aliases: ["시재", "마약시재", "재고", "마약 재고"],
    category: "medication",
    definition: "금고에 남아 있어야 할 마약류 수량.",
    informal: true,
    formal: "마약류 재고",
    pitfall: "수량이 안 맞으면 즉시 보고한다. 혼자 맞춰 보려다 시간이 지나면 경위 확인이 불가능해진다.",
  },
  {
    id: "drug-dispense",
    ko: "약제 불출",
    en: "dispensing",
    aliases: ["불출", "약 불출", "불출됨"],
    category: "medication",
    definition: "약국에서 병동으로 약이 나오는 것.",
    informal: true,
    formal: "약제 불출",
  },
  {
    id: "drug-return",
    ko: "약제 반납",
    en: "drug return",
    aliases: ["반납", "약 반납", "반납함"],
    category: "medication",
    definition: "쓰지 않은 약을 약국으로 돌려보내는 것.",
    informal: true,
    formal: "약제 반납",
  },
  {
    id: "scrub-nurse",
    ko: "소독간호사",
    en: "scrub nurse",
    aliases: ["스크럽", "스크럽널스", "소독간호사"],
    category: "role",
    definition: "수술장에서 멸균 영역 안에서 기구를 다루는 간호사.",
    informal: true,
    formal: "소독간호사",
  },
  {
    id: "circulating-nurse",
    ko: "순환간호사",
    en: "circulating nurse",
    aliases: ["서큘레이팅", "써큘", "순환간호사", "외회전"],
    category: "role",
    definition: "수술장에서 멸균 영역 밖의 일을 맡는 간호사.",
    informal: true,
    formal: "순환간호사",
  },
  {
    id: "transport-staff",
    ko: "이송요원",
    en: "patient transporter",
    aliases: ["이송", "이송요원", "이송기사"],
    category: "role",
    definition: "환자를 검사실·수술실 등으로 옮기는 직원.",
    informal: true,
    formal: "이송요원",
  },
  {
    id: "nursing-assistant",
    ko: "간호조무사",
    en: "nursing assistant",
    aliases: ["조무사", "간조", "널스에이드"],
    category: "role",
    definition: "간호사의 지도 아래 간호 업무를 보조하는 인력.",
    informal: true,
    formal: "간호조무사",
    pitfall: "위임할 수 있는 업무의 범위가 법으로 정해져 있다. 투약·사정처럼 위임 불가한 일을 넘기면 간호사가 책임진다.",
  },
  {
    id: "infection-control-team",
    ko: "감염관리실",
    en: "infection control team",
    aliases: ["감염관리실", "감관", "감염팀"],
    category: "role",
    definition: "원내 감염 감시와 격리 지침을 관장하는 부서.",
  },
  {
    id: "qi-team",
    ko: "적정진료팀",
    en: "quality improvement team",
    aliases: ["큐아이", "QI실", "적정진료실"],
    category: "role",
    definition: "의료 질 향상과 환자안전 활동을 담당하는 부서. 안전사고 보고가 모이는 곳.",
  },

  // ── 근무를 말할 때 ──────────────────────────────────────
  {
    id: "long-day",
    ko: "연장 근무",
    en: "long day",
    aliases: ["롱데이", "롱듀티", "연장근무"],
    category: "shift",
    definition: "정규 근무 시간을 넘겨 이어서 일하는 것.",
    informal: true,
    formal: "연장 근무",
    pitfall: "연장근로는 가산수당 대상이다(근로기준법 제56조). 실제 퇴근 시각을 스스로 기록해 두는 편이 좋다.",
  },
  {
    id: "duty-change",
    ko: "근무 교환",
    en: "shift swap",
    aliases: ["듀티체인지", "듀티 바꾸다", "근무 바꾸기", "체인지"],
    category: "shift",
    definition: "동료와 근무를 서로 맞바꾸는 것.",
    informal: true,
    formal: "근무 교환",
  },
  {
    id: "on-call",
    ko: "대기 근무",
    en: "on-call",
    aliases: ["온콜", "대기", "온콜대기"],
    category: "shift",
    definition: "쉬는 중이지만 호출되면 나와야 하는 상태.",
    informal: true,
    formal: "대기 근무",
    pitfall: "호출되어 실제로 일한 시간은 근로시간이다. 대기 자체의 처우는 취업규칙을 확인한다.",
  },
  {
    id: "deposit-off",
    ko: "적립 휴무",
    en: "banked off day",
    aliases: ["뎁오", "뎁오프", "적립오프"],
    category: "shift",
    definition:
      "쓰지 않고 모아 두었다가 나중에 붙여 쓰는 휴무를 부르는 말. 병원마다 운영 방식과 부르는 이름이 다르다.",
    informal: true,
    formal: "적립 휴무",
  },
  {
    id: "half-day",
    ko: "반차",
    en: "half day",
    aliases: ["하프", "반차", "반휴"],
    category: "shift",
    definition: "하루의 절반만 쉬는 것.",
    informal: true,
    formal: "반차",
  },
  {
    id: "seniority-pressure",
    ko: "텃세",
    en: "hazing by seniority",
    aliases: ["텃세", "군기", "기수 문화"],
    category: "shift",
    definition: "먼저 온 사람이 나중에 온 사람을 눌러 서열을 세우는 분위기.",
    informal: true,
    formal: "위계에 따른 부당한 압력",
    pitfall:
      "'원래 그런 것'으로 넘어가는 사이 근로기준법 제76조의2의 직장 내 괴롭힘 요건을 채우는 경우가 있다. 반복되면 기록으로 남겨 둔다.",
  },
  {
    id: "mentor-senior",
    ko: "사수",
    en: "assigned senior",
    aliases: ["사수", "우리 사수", "사수쌤"],
    category: "role",
    definition: "공식 프리셉터가 아니어도 사실상 나를 가르치는 선배를 부르는 말.",
    informal: true,
    formal: "지도 선배",
  },
  {
    id: "burnout",
    ko: "소진",
    en: "burnout",
    aliases: ["번아웃", "소진", "탈진"],
    category: "shift",
    definition: "지속된 스트레스로 정서적·신체적으로 고갈된 상태.",
    informal: true,
    formal: "직무 소진",
    pitfall:
      "의지 문제가 아니라 근무 환경의 결과인 경우가 많다. 근무표·연속근무·야간 횟수와 함께 보면 원인이 보인다.",
  },

  // ── 근무표·스케줄 문화 (2026-08 보강) ─────────────────────
  // 병동 대화에서 근무 이야기의 비중은 임상만큼 크다. 낱말은 병원마다
  // 조금씩 다르므로, 정의에는 "무엇을 가리키는가"만 적고 단정하지 않는다.
  {
    id: "duty-table",
    ko: "번표",
    en: "duty roster",
    aliases: ["번표", "듀티표", "근무표"],
    category: "shift",
    definition: "한 달 근무를 번갈아 짠 표. 데이·이브닝·나이트·오프가 여기서 정해진다.",
    informal: true,
    formal: "근무표",
  },
  {
    id: "shift-pattern-naode",
    ko: "나오데",
    en: "N-Off-D pattern",
    aliases: ["나오데", "나오이", "데나오"],
    category: "shift",
    definition:
      "근무 조합을 첫 글자로 줄여 부르는 말. 나오데는 나이트-오프-데이 — 밤샘 뒤 하루 쉬고 바로 아침 출근이라 몸이 가장 상하는 배치로 꼽힌다.",
    informal: true,
    formal: "나이트-오프-데이 연속 근무",
    pitfall:
      "나오데·이브데이 같은 배치가 반복되면 수면 주기가 무너진다. 근무 간 11시간 휴식 규정과 함께 봐야 한다.",
  },
  {
    id: "double-duty",
    ko: "더블듀티",
    en: "double duty",
    aliases: ["더블듀티", "더블", "이브데이"],
    category: "shift",
    definition: "하루에 두 근무를 이어 서는 것. 이브데이는 이브닝 다음 날 바로 데이로 출근하는 배치.",
    informal: true,
    formal: "연속 근무",
  },
  {
    id: "day-overrun",
    ko: "데이사다시",
    en: "day-shift overrun",
    aliases: ["데이사다시", "사다시"],
    category: "shift",
    definition: "데이 근무에서 인계·일이 안 끝나 정시를 넘겨 남는 것. 일본어 잔재 표현.",
    informal: true,
    formal: "초과 근무",
    pitfall: "반복되면 그건 개인 속도 문제가 아니라 업무량 문제다. 남은 시간을 기록해 두면 근거가 된다.",
  },
  {
    id: "pongdang",
    ko: "퐁당퐁당",
    en: "alternating schedule",
    aliases: ["퐁당퐁당", "퐁당"],
    category: "shift",
    definition: "근무-오프-근무-오프처럼 하루 걸러 출근하는 배치를 부르는 말.",
    informal: true,
    formal: "격일 근무",
  },
  {
    id: "night-fix",
    ko: "나이트 픽스",
    en: "fixed night",
    aliases: ["나이트픽스", "나픽", "픽스"],
    category: "shift",
    definition: "교대 없이 나이트만 고정으로 서는 근무 형태.",
    informal: true,
    formal: "야간 전담 근무",
    pitfall: "픽스라는 말만으로는 어떤 근무 고정인지 모른다. 병동에서 확인이 필요하다.",
  },
  {
    id: "hwanta",
    ko: "환타",
    en: "patient surge",
    aliases: ["환타"],
    category: "workflow",
    definition: "환자가 물밀듯 몰려와 눈코 뜰 새 없이 바쁜 상태를 이르는 말.",
    informal: true,
    formal: "환자 급증",
    pitfall: "음료 이름과 같아 전사에서 헷갈릴 수 있다. 병동 문맥에서는 거의 항상 이 뜻이다.",
  },
  {
    id: "watered-firewood",
    ko: "물 부은 장작",
    en: "unmanageable mess",
    aliases: ["물부은장작", "물 부은 장작"],
    category: "workflow",
    definition: "일이나 환자 상태가 겉잡을 수 없이 꼬여 어찌할 도리가 없는 상황을 이르는 말.",
    informal: true,
    formal: "업무 과중 상태",
  },
  {
    id: "byungbabyung",
    ko: "병바병",
    en: "hospital-by-hospital",
    aliases: ["병바병", "부바부"],
    category: "workflow",
    definition: "'병원 바이 병원' — 규정과 분위기가 병원·부서마다 전혀 다르다는 말. 부바부는 부서 단위.",
    informal: true,
    formal: "기관별 상이",
    pitfall: "선배마다 말이 다를 때 그 이유가 대개 이것이다. 우리 병동 기준을 확인하고 기록해 두는 것이 답이다.",
  },
];
