import type { LexiconEntry } from "./types.js";

/**
 * 병동 은어 / 업무 흐름 / 역할 / 듀티 용어.
 *
 * 왜 은어를 따로 다루는가
 * ----------------------
 * 1. **알아들어야 산다.** 인계의 절반은 은어다. 사전에 없으니 신규는 물어볼
 *    타이밍을 놓치고, 못 알아들은 채로 넘어간 항목이 그대로 사고가 된다.
 * 2. **기록에 쓰면 안 된다.** "옵세했음", "멘탈 다운"은 대화에서는 통해도
 *    간호기록에 쓰면 법적 문서로서 결함이 된다. 그래서 `informal`과 `formal`을
 *    쌍으로 갖고 있고, 보고서 생성기가 이 매핑으로 자동 치환한다.
 * 3. **은어는 병원마다 다르다.** 아래는 국내 병동에서 널리 통용되는 것 위주이며,
 *    사용자가 자기 병동 표현을 추가할 수 있도록 사용자 사전과 합쳐서 쓴다.
 */
export const SLANG_TERMS: LexiconEntry[] = [
  // ── 보고 / 인계 ──────────────────────────────────────────
  {
    id: "notify",
    ko: "보고",
    en: "notify",
    aliases: ["노티", "노티하다", "노티드리다", "노티파이"],
    category: "documentation",
    definition: "의사에게 환자 상태 변화나 검사 결과를 알리는 것.",
    informal: true,
    formal: "의사에게 보고",
    pitfall:
      "노티는 '말했다'로 끝나지 않는다. 누구에게, 몇 시에, 무엇을 보고했고, 어떤 지시를 받았는지가 전부 기록되어야 한다. 신규가 가장 자주 혼나는 지점이자 실제로 가장 중요한 지점이다.",
    sources: ["koiha"],
  },
  {
    id: "handover",
    ko: "인계",
    en: "handover / handoff",
    aliases: ["인계", "인수인계", "핸드오버", "인계받다", "인계주다"],
    category: "documentation",
    definition: "근무 교대 시 환자 정보와 남은 업무를 다음 근무자에게 넘기는 과정.",
    pitfall:
      "인계에서 빠진 항목은 다음 근무 8시간 동안 아무도 모른다. 못 알아들은 건 그 자리에서 되묻는 것이 정답이다. 다시 물어보는 것보다 모르고 넘어가는 게 훨씬 위험하다.",
    sources: ["koiha"],
  },
  {
    id: "sbar",
    ko: "SBAR 보고형식",
    en: "Situation-Background-Assessment-Recommendation",
    abbr: "SBAR",
    aliases: ["에스바", "에스비에이알", "에스바알"],
    category: "documentation",
    definition:
      "상황(S)-배경(B)-사정(A)-제안(R) 순서로 보고하는 표준 의사소통 구조. 노티할 때 이 순서로 말하면 빠뜨리지 않는다.",
    pitfall:
      "R(제안)을 빼먹는 신규가 많다. '어떻게 할까요'가 아니라 '~를 해도 될까요'까지 말하는 연습이 노티 공포를 줄인다.",
    sources: ["koiha"],
  },
  {
    id: "order",
    ko: "처방",
    en: "order",
    aliases: ["오더", "처방", "오더받다", "오더내다"],
    category: "documentation",
    definition: "의사가 낸 진료 지시. 투약·검사·처치의 법적 근거가 된다.",
    informal: true,
    formal: "처방",
    pitfall: "처방 없이 시행한 처치는 근거가 없다. 구두처방은 반드시 복창 확인 후 정해진 시간 안에 전산 처방으로 남긴다.",
  },
  {
    id: "verbal-order",
    ko: "구두처방",
    en: "verbal order",
    abbr: "V/O",
    aliases: ["브이오", "구두오더", "구두처방", "버벌오더"],
    category: "documentation",
    definition: "응급 상황 등에서 의사가 말로 낸 처방.",
    pitfall:
      "받아적고 그대로 되읽어 확인(read-back)하는 것이 필수. 이후 정해진 시간 내 처방 입력과 서명을 받아야 하며, 이 절차가 빠지면 시행한 간호사가 책임을 진다.",
    sources: ["koiha"],
  },
  {
    id: "observation",
    ko: "경과 관찰",
    en: "observation",
    aliases: ["옵세", "옵져베이션", "옵서베이션", "옵세하다", "관찰"],
    category: "workflow",
    definition: "즉시 처치하지 않고 상태 변화를 지켜보는 것.",
    informal: true,
    formal: "경과 관찰",
    pitfall:
      "'옵세'는 아무것도 안 한다는 뜻이 아니다. 무엇을, 얼마 간격으로, 어떤 수치가 되면 보고할지가 정해져야 관찰이다. 그 기준을 못 들었으면 물어봐야 한다.",
  },
  {
    id: "rounding",
    ko: "회진",
    en: "rounding",
    aliases: ["라운딩", "라운드", "회진", "라운딩돌다"],
    category: "workflow",
    definition: "의료진이 병실을 돌며 환자 상태를 확인하는 것. 간호사의 정기 병실 순회도 포함한다.",
    pitfall: "회진 때 나온 계획 변경은 그 자리에서 메모한다. 나중에 기억으로 복원하려다 빠뜨리는 항목이 반드시 생긴다.",
  },
  {
    id: "consult",
    ko: "협진",
    en: "consultation",
    aliases: ["컨설트", "컨설", "협진", "컨설트내다"],
    category: "workflow",
    definition: "다른 진료과에 진료를 의뢰하는 것.",
    informal: true,
    formal: "협진 의뢰",
  },
  {
    id: "transfer",
    ko: "전동",
    en: "transfer",
    aliases: ["트랜스퍼", "전동", "병동이동", "전동가다"],
    category: "workflow",
    definition: "환자가 다른 병동·병원으로 옮겨가는 것.",
    pitfall: "라인·배액관·투약 중인 약·마지막 활력징후를 인계지에 정리한다. 전동 중 사고는 인계 누락에서 온다.",
  },
  {
    id: "discharge",
    ko: "퇴원",
    en: "discharge",
    abbr: "D/C",
    aliases: ["디씨", "디시", "퇴원", "디씨나가다"],
    category: "workflow",
    definition: "환자가 입원 치료를 마치고 병원을 떠나는 것.",
    pitfall:
      "'D/C'는 discontinue(중단)의 약어이기도 하다. 문맥이 애매하면 반드시 되묻는다. 라인 D/C와 환자 D/C를 헷갈리면 사고가 난다.",
  },
  {
    id: "operation",
    ko: "수술",
    en: "operation",
    abbr: "OP",
    aliases: ["오피", "오퍼레이션", "수술", "옵"],
    category: "workflow",
    definition: "수술. 수술 전(pre-op)과 수술 후(post-op)로 나누어 준비와 간호가 달라진다.",
    pitfall: "수술 전 확인 목록(금식·동의서·제모·수술부위 표시·의치·장신구)은 하나라도 빠지면 수술이 지연된다.",
    sources: ["koiha"],
  },
  {
    id: "portable-xray",
    ko: "이동식 방사선촬영",
    en: "portable X-ray",
    aliases: ["포터블", "포터블찍다", "이동촬영"],
    category: "workflow",
    definition: "환자를 옮기지 않고 병실에서 시행하는 방사선 촬영.",
    informal: true,
    formal: "이동식 방사선촬영",
    pitfall: "촬영 시 주변 환자·보호자를 보호한다. 임신 가능성 확인은 촬영 전 필수 문항이다.",
  },
  {
    id: "line-insertion",
    ko: "정맥로 확보",
    en: "IV cannulation",
    aliases: ["라인잡다", "라인확보", "아이브이잡다", "혈관잡다"],
    category: "procedure",
    definition: "말초정맥에 카테터를 넣어 주입 경로를 만드는 것.",
    informal: true,
    formal: "말초정맥로 확보",
    pitfall: "여러 번 실패하면 자책하지 말고 교대한다. 반복 천자는 환자 손상과 시간 손실이 더 크다.",
  },
  {
    id: "line-infiltration",
    ko: "정맥주입 침윤",
    en: "infiltration / extravasation",
    aliases: ["라인터졌다", "라인샜다", "인필트레이션", "새다", "부었다"],
    category: "condition",
    definition: "주입액이 혈관 밖 조직으로 새어 나간 상태. 발적·부종·통증이 나타난다.",
    informal: true,
    formal: "정맥주입 침윤(발적/부종 동반)",
    pitfall:
      "항암제·고농도 약물이 새면 조직 괴사로 이어진다(일혈). 즉시 중단하고 라인을 유지한 채 잔여 약물을 흡인한 뒤 보고한다.",
    sources: ["khna-guideline"],
  },
  {
    id: "gauge",
    ko: "게이지",
    en: "gauge",
    abbr: "G",
    aliases: ["게이지", "지", "이십사게이지", "니들게이지"],
    category: "device",
    definition: "바늘 굵기 단위. 숫자가 클수록 가늘다(24G가 18G보다 가늘다).",
    pitfall: "수혈과 급속 수액은 굵은 게이지가 필요하다. 가는 라인으로 수혈하면 용혈 위험이 있다.",
  },

  // ── 역할 / 직역 ─────────────────────────────────────────
  {
    id: "preceptor",
    ko: "프리셉터",
    en: "preceptor",
    aliases: ["프리셉터", "교육담당"],
    category: "role",
    definition: "신규간호사의 현장 교육을 일대일로 담당하는 경력 간호사.",
    pitfall:
      "프리셉터의 지도 방식은 사람마다 크게 다르다. 지도와 괴롭힘의 경계가 흐려지면 기록으로 남겨두는 것이 스스로를 지키는 방법이다.",
    sources: ["knahr"],
  },
  {
    id: "preceptee",
    ko: "프리셉티",
    en: "preceptee",
    aliases: ["프리셉티", "프리셉티간호사", "신규"],
    category: "role",
    definition: "프리셉터에게 교육을 받는 신규간호사.",
  },
  {
    id: "charge-nurse",
    ko: "책임간호사",
    en: "charge nurse",
    aliases: ["차지", "차지간호사", "책임"],
    category: "role",
    definition: "해당 근무조의 병동 운영과 인력 배치를 총괄하는 간호사.",
    informal: true,
    formal: "책임간호사",
  },
  {
    id: "acting-nurse",
    ko: "실무담당간호사",
    en: "acting nurse",
    aliases: ["액팅", "액팅간호사"],
    category: "role",
    definition: "직접 처치와 투약 등 실무를 담당하는 간호사. 차지와 대비되는 역할 구분.",
    informal: true,
    formal: "실무담당간호사",
  },
  {
    id: "head-nurse",
    ko: "수간호사",
    en: "head nurse / unit manager",
    aliases: ["수쌤", "수간", "수간호사", "유엠", "파트장"],
    category: "role",
    definition: "병동 관리자. 인력·물품·교육·근무표를 총괄한다.",
    informal: true,
    formal: "수간호사",
    pitfall: "직장 내 괴롭힘 신고는 통상 관리자를 통해 접수되지만, 가해자가 관리자인 경우 별도 창구(고충처리·인권센터)를 이용할 수 있다.",
    sources: ["knahr", "law-go-kr"],
  },
  {
    id: "resident",
    ko: "전공의",
    en: "resident",
    abbr: "R",
    aliases: ["알", "레지던트", "알원", "알투", "레지"],
    category: "role",
    definition: "전문의 자격 취득을 위해 수련 중인 의사. 연차를 R1~R4로 부른다.",
    informal: true,
    formal: "전공의",
  },
  {
    id: "intern",
    ko: "인턴",
    en: "intern",
    aliases: ["인턴", "아이", "인턴선생님"],
    category: "role",
    definition: "의사면허 취득 후 1년간 각 과를 돌며 수련하는 의사.",
  },

  // ── 근무 / 듀티 은어 ────────────────────────────────────
  {
    id: "duty",
    ko: "근무",
    en: "duty",
    aliases: ["듀티", "듀티표", "근무표", "듀티나왔다"],
    category: "shift",
    definition: "교대근무 배정. 통상 데이(D)·이브닝(E)·나이트(N)·오프(O)로 구성된다.",
    informal: true,
    formal: "근무 배정",
  },
  {
    id: "day-shift",
    ko: "데이 근무",
    en: "day shift",
    abbr: "D",
    aliases: ["데이", "데이번", "낮번", "데이근무"],
    category: "shift",
    definition: "오전 근무조. 통상 07:00 전후 시작해 15:00 전후 종료(병원마다 다름).",
    informal: true,
    formal: "주간 근무",
    pitfall: "인계 준비 때문에 실제 출근은 근무 시작보다 30~60분 이르다. 이 시간이 근로시간으로 인정되는지는 확인해볼 문제다.",
    sources: ["law-go-kr"],
  },
  {
    id: "evening-shift",
    ko: "이브닝 근무",
    en: "evening shift",
    abbr: "E",
    aliases: ["이브닝", "이브", "저녁번", "이브닝근무"],
    category: "shift",
    definition: "오후 근무조. 통상 15:00 전후 시작해 23:00 전후 종료.",
    informal: true,
    formal: "저녁 근무",
  },
  {
    id: "night-shift",
    ko: "나이트 근무",
    en: "night shift",
    abbr: "N",
    aliases: ["나이트", "나이트번", "밤번", "나이트근무"],
    category: "shift",
    definition: "야간 근무조. 통상 23:00 전후 시작해 다음날 07:00 전후 종료.",
    informal: true,
    formal: "야간 근무",
    pitfall:
      "근로기준법상 야간근로(22시~06시)는 가산수당 대상이다. 임신 중이거나 산후 1년 미만이면 야간·휴일 근로에 별도의 제한과 동의 절차가 있다.",
    sources: ["law-go-kr"],
  },
  {
    id: "off-duty",
    ko: "휴무",
    en: "off",
    abbr: "O",
    aliases: ["오프", "휴무", "쉬는날", "오프날"],
    category: "shift",
    definition: "근무가 배정되지 않은 날.",
    informal: true,
    formal: "휴무",
  },
  {
    id: "night-off",
    ko: "나이트 후 휴무",
    en: "post-night off",
    aliases: ["나오", "나이트오프", "엔오"],
    category: "shift",
    definition: "나이트 근무를 마친 뒤 이어지는 휴무. 실질 휴식은 퇴근 후 반나절 정도인 경우가 많다.",
    informal: true,
    formal: "야간근무 후 휴무",
    pitfall: "나이트 퇴근일은 '쉬는 날'로 세기 어렵다. 실제 휴식 시간을 따로 계산해봐야 자기 피로도를 알 수 있다.",
  },
  {
    id: "consecutive-nights",
    ko: "연속 나이트",
    en: "consecutive night shifts",
    aliases: ["투나잇", "쓰리나잇", "연속나이트", "나이트연속"],
    category: "shift",
    definition: "나이트를 2일 이상 연달아 서는 것. 투나잇=2연속, 쓰리나잇=3연속.",
    informal: true,
    formal: "연속 야간근무",
    pitfall: "연속 야간근무는 누적 피로와 투약오류 위험을 함께 올린다. 횟수를 기록해두면 근무표 협의의 근거가 된다.",
  },
  {
    id: "back-duty",
    ko: "짧은 간격 연속근무",
    en: "quick return",
    aliases: ["백듀티", "역듀티"],
    category: "shift",
    definition:
      "앞 근무 종료와 다음 근무 시작 사이 휴식이 짧게 붙은 배정. 예: 이브닝 퇴근 후 다음날 데이 출근.",
    informal: true,
    formal: "근무 간 휴식이 짧은 연속 배정",
    pitfall: "실제 수면 가능 시간이 5시간 미만이 되는 경우가 흔하다. 발생 횟수를 앱이 자동 집계해준다.",
  },
  {
    id: "manpower-gap",
    ko: "인력 결원",
    en: "staffing gap",
    aliases: ["빵꾸", "구멍", "펑크", "빵꾸났다"],
    category: "shift",
    definition: "결원으로 근무표에 자리가 빈 것. 대개 오프인 사람이 불려 나와 메운다.",
    informal: true,
    formal: "인력 결원",
    pitfall: "휴무일 호출 근무는 근로시간이다. 실제로 일한 시간은 기록해두는 편이 좋다.",
    sources: ["law-go-kr"],
  },
  {
    id: "taeum",
    ko: "태움",
    en: "workplace bullying among nurses",
    aliases: ["태움", "태워지다", "갈굼"],
    category: "shift",
    definition:
      "선배 간호사가 후배를 가르친다는 명목으로 반복적으로 모욕·질책·따돌림을 가하는 관행. '영혼이 재가 될 때까지 태운다'는 표현에서 왔다.",
    informal: true,
    formal: "직장 내 괴롭힘",
    pitfall:
      "근로기준법 제76조의2가 금지하는 직장 내 괴롭힘에 해당할 수 있다. 지위·관계 우위를 이용해 업무상 적정범위를 넘어 신체적·정신적 고통을 주거나 근무환경을 악화시키는 행위가 요건이다. 교육적 지적과의 구분은 '업무상 적정범위'에서 갈린다.",
    sources: ["law-go-kr", "knahr", "moel"],
  },
];
