import type { LexiconEntry } from "./types.js";

/**
 * 임상 용어 - 사정 / 처치 / 기구 / 검사 / 상태 / 응급.
 *
 * aliases에 "틀린 표기"를 일부러 넣어둔 것에 주의. 이건 오타가 아니라
 * ASR이 실제로 그렇게 받아적는 형태이며, 교정 엔진의 입력 앵커 역할을 한다.
 */
export const CLINICAL_TERMS: LexiconEntry[] = [
  // ── 사정 / 활력징후 ──────────────────────────────────────
  {
    id: "vital-sign",
    ko: "활력징후",
    en: "vital signs",
    abbr: "V/S",
    aliases: ["브이에스", "바이탈", "바이탈사인"],
    category: "assessment",
    definition:
      "체온·맥박·호흡·혈압(및 산소포화도)을 묶어 부르는 말. 환자 상태 변화를 가장 먼저 드러내는 지표.",
    pitfall:
      "수치 하나만 보고 넘기지 말 것. 이전 값과의 '추세'가 단일 수치보다 중요하다. 평소보다 확연히 벗어나면 정상 범위 안이어도 노티 대상이다.",
    sources: ["khna-guideline"],
  },
  {
    id: "blood-pressure",
    ko: "혈압",
    en: "blood pressure",
    abbr: "BP",
    aliases: ["비피"],
    category: "assessment",
    definition: "동맥 내 혈액이 혈관벽에 가하는 압력. 수축기/이완기로 기록한다.",
    pitfall: "커프 크기가 팔 둘레에 맞지 않으면 값이 통째로 틀어진다. 마비측·수액측·투석 션트측은 피한다.",
  },
  {
    id: "heart-rate",
    ko: "맥박",
    en: "heart rate",
    abbr: "HR",
    aliases: ["에이치알", "하트레이트", "펄스", "피알"],
    category: "assessment",
    definition: "분당 심박수. 정상 성인 60~100회/분.",
    pitfall: "부정맥 환자는 요골동맥 촉진값과 심첨 청진값이 다르다(맥박결손). 불규칙하면 1분 전체를 센다.",
  },
  {
    id: "respiration-rate",
    ko: "호흡수",
    en: "respiratory rate",
    abbr: "RR",
    aliases: ["알알", "호흡"],
    category: "assessment",
    definition: "분당 호흡 횟수. 정상 성인 12~20회/분.",
    pitfall:
      "가장 자주 대충 기록되면서 악화를 가장 먼저 알려주는 지표. 실제로 세지 않고 추정해 적는 습관은 조기경보를 통째로 날린다.",
  },
  {
    id: "body-temperature",
    ko: "체온",
    en: "body temperature",
    abbr: "BT",
    aliases: ["비티"],
    category: "assessment",
    definition: "심부 체온의 추정치. 측정 부위(고막/액와/구강/직장)에 따라 기준이 다르다.",
    pitfall: "측정 부위를 기록에 남기지 않으면 다음 근무자가 비교할 수 없다.",
  },
  {
    id: "spo2",
    ko: "산소포화도",
    en: "oxygen saturation",
    abbr: "SpO2",
    aliases: ["에스피오투", "사츄", "새츄레이션"],
    category: "assessment",
    definition: "맥박산소측정기로 잰 동맥혈 산소포화도. 정상 95% 이상.",
    pitfall:
      "말초 순환이 나쁘거나(쇼크·저체온) 매니큐어·심한 부종이 있으면 실제보다 낮게 나온다. 일산화탄소 중독에서는 반대로 정상처럼 나온다.",
  },
  {
    id: "intake-output",
    ko: "섭취량/배설량",
    en: "intake and output",
    abbr: "I/O",
    aliases: ["아이오", "인아웃", "아이앤오", "인테이크아웃풋"],
    category: "assessment",
    definition: "일정 시간 동안 들어간 수분과 나간 수분의 합계. 체액 균형 판단의 기본 자료.",
    pitfall:
      "수액·경관영양·약물 희석액까지 전부 intake다. 배액관·구토·설사도 output이다. 한 항목만 빠져도 균형 계산이 무의미해진다.",
    sources: ["khna-guideline"],
  },
  {
    id: "ekg",
    ko: "심전도",
    en: "electrocardiogram",
    abbr: "EKG",
    aliases: ["이케이지", "이씨지", "심전도검사"],
    category: "assessment",
    definition: "심장의 전기적 활동을 기록한 검사. 12유도가 표준.",
    pitfall: "전극 위치가 어긋나면 허혈 소견처럼 보인다. 흉통 시 EKG는 STAT이며 촬영 시각을 반드시 기록한다.",
  },
  {
    id: "mental-status",
    ko: "의식수준",
    en: "mental status / level of consciousness",
    abbr: "LOC",
    aliases: ["멘탈", "멘탈스테이터스", "의식상태", "엘오씨"],
    category: "assessment",
    definition:
      "각성-명료(alert), 기면(drowsy), 혼미(stupor), 반혼수(semicoma), 혼수(coma)로 표현하는 의식 단계.",
    pitfall: "'멘탈 다운'처럼 뭉뚱그리지 말고 어떤 자극에 어떻게 반응했는지를 그대로 기록한다.",
  },
  {
    id: "gcs",
    ko: "글래스고 혼수 척도",
    en: "Glasgow Coma Scale",
    abbr: "GCS",
    aliases: ["지씨에스", "글라스고", "글래스고"],
    category: "assessment",
    definition: "눈뜨기(E4)·언어반응(V5)·운동반응(M6)을 합산해 3~15점으로 의식수준을 수량화한 도구.",
    pitfall: "총점만 적으면 정보가 사라진다. E/V/M을 나눠 적어야 어느 영역이 나빠졌는지 보인다.",
  },
  {
    id: "pain-nrs",
    ko: "숫자통증등급",
    en: "Numeric Rating Scale",
    abbr: "NRS",
    aliases: ["엔알에스", "통증점수", "통증스케일", "페인스케일"],
    category: "assessment",
    definition: "환자가 통증을 0(없음)~10(최악)으로 스스로 매기는 자가보고 척도.",
    pitfall:
      "간호사가 추정해 매기는 순간 자가보고가 아니게 된다. 의사소통이 어려운 대상자는 행동관찰 도구를 따로 쓴다.",
    sources: ["khna-guideline"],
  },
  {
    id: "blood-sugar-test",
    ko: "혈당검사",
    en: "blood sugar test",
    abbr: "BST",
    aliases: ["비에스티", "혈당체크", "슈가체크", "당체크"],
    category: "assessment",
    definition: "간이 혈당측정기로 모세혈관 혈당을 재는 것.",
    pitfall: "첫 방울은 닦아내고 두 번째 방울로 잰다. 알코올이 마르기 전에 찌르면 값이 낮게 나온다.",
  },
  {
    id: "morse-fall-scale",
    ko: "낙상위험 사정도구",
    en: "Morse Fall Scale",
    abbr: "MFS",
    aliases: ["모스", "모스폴스케일", "낙상사정", "낙상스케일"],
    category: "assessment",
    definition: "낙상력·이차진단·보행보조·정맥주입·걸음걸이·의식상태 6항목으로 낙상 위험을 점수화하는 도구.",
    pitfall: "입원 시 1회로 끝내면 안 된다. 상태 변화·전동·낙상 발생 후에는 반드시 재사정한다.",
    sources: ["khna-guideline", "koiha"],
  },
  {
    id: "braden-scale",
    ko: "욕창위험 사정도구",
    en: "Braden Scale",
    abbr: "",
    aliases: ["브레이든", "브레이든스케일", "욕창사정"],
    category: "assessment",
    definition: "감각인지·습기·활동·기동성·영양·마찰과전단 6항목으로 욕창 위험을 점수화하는 도구. 낮을수록 고위험.",
    pitfall: "점수만 매기고 중재를 연결하지 않으면 사정의 의미가 없다. 위험군은 체위변경 주기를 기록으로 남긴다.",
    sources: ["khna-guideline"],
  },

  // ── 처치 / 술기 ──────────────────────────────────────────
  {
    id: "suction",
    ko: "흡인",
    en: "suction",
    aliases: ["석션", "썩션", "흡인간호"],
    category: "procedure",
    definition: "기도나 구강의 분비물을 음압으로 제거하는 술기.",
    pitfall:
      "1회 흡인은 10~15초 이내, 넣을 때는 음압을 걸지 않는다. 전후 산소화가 원칙이며 저산소증·부정맥을 관찰한다.",
    sources: ["khna-guideline"],
  },
  {
    id: "dressing",
    ko: "드레싱",
    en: "dressing",
    aliases: ["드레싱", "상처드레싱", "소독"],
    category: "procedure",
    definition: "상처를 세척하고 피복재를 적용해 보호·치유 환경을 만드는 처치.",
    pitfall: "드레싱 교환 때마다 상처 크기·삼출물 양상·주변 피부를 기록해야 경과 비교가 가능하다.",
    sources: ["khna-guideline"],
  },
  {
    id: "enema",
    ko: "관장",
    en: "enema",
    aliases: ["에네마", "관장하기", "글리세린관장"],
    category: "procedure",
    definition: "직장으로 용액을 주입해 배변을 유도하거나 장을 비우는 처치.",
    pitfall: "좌측위(심스 체위)로 시행한다. 서맥·복통·출혈이 있으면 즉시 중단하고 보고한다.",
  },
  {
    id: "restraint",
    ko: "억제대",
    en: "physical restraint",
    aliases: ["리스트레인", "억제", "신체억제", "억제대적용"],
    category: "procedure",
    definition: "환자 안전을 위해 신체 움직임을 제한하는 기구. 최후의 수단으로만 쓴다.",
    pitfall:
      "처방·동의·적용 사유·적용 시각·순환 확인 주기·해제 시도 기록이 모두 필요하다. 하나라도 빠지면 법적으로 문제가 된다.",
    sources: ["khna-guideline", "koiha"],
  },
  {
    id: "position-change",
    ko: "체위변경",
    en: "position change / turning",
    aliases: ["터닝", "체위변경", "포지션체인지", "돌려눕히기"],
    category: "procedure",
    definition: "압력을 분산해 욕창을 예방하고 폐 확장을 돕기 위해 자세를 바꾸는 것.",
    pitfall: "통상 2시간 간격이 기준이지만 위험도와 지지면에 따라 달라진다. 시행 시각을 기록해야 근거가 된다.",
    sources: ["khna-guideline"],
  },
  {
    id: "hand-hygiene",
    ko: "손위생",
    en: "hand hygiene",
    aliases: ["핸드워싱", "손씻기", "손소독"],
    category: "procedure",
    definition: "의료관련감염 예방의 가장 기본이자 효과가 큰 행위. WHO 5 moments를 기준으로 한다.",
    pitfall: "장갑은 손위생을 대체하지 않는다. 장갑 착용 전후 모두 손위생이 필요하다.",
    sources: ["kdca-hai", "koiha"],
  },
  {
    id: "aseptic-technique",
    ko: "무균술",
    en: "aseptic technique",
    aliases: ["어셉틱", "무균조작", "소독술"],
    category: "procedure",
    definition: "미생물이 없는 상태를 유지하며 시행하는 조작. 외과적 무균술과 내과적 무균술로 나뉜다.",
    pitfall: "멸균영역은 허리 위·시야 안에서만 유지된다. 등을 돌리는 순간 오염으로 간주한다.",
    sources: ["kdca-hai"],
  },

  // ── 기구 / 라인 ──────────────────────────────────────────
  {
    id: "foley-catheter",
    ko: "유치도뇨관",
    en: "Foley catheter",
    aliases: ["폴리", "폴리카테터", "유치도뇨"],
    category: "device",
    definition: "방광에 유치해 소변을 지속 배출시키는 도뇨관. 풍선으로 방광 내에 고정한다.",
    pitfall:
      "소변주머니를 방광보다 높이 들면 역류로 감염된다. 유치 기간이 길수록 요로감염 위험이 올라가므로 매일 필요성을 재평가한다.",
    sources: ["khna-guideline", "kdca-hai"],
  },
  {
    id: "levin-tube",
    ko: "비위관",
    en: "Levin tube / nasogastric tube",
    abbr: "L-tube",
    aliases: ["엘튜브", "레빈튜브", "엔지튜브", "비위관삽입"],
    category: "device",
    definition: "코를 통해 위까지 넣는 관. 영양공급·투약·위 내용물 배액에 쓴다.",
    pitfall:
      "주입 전 위치 확인은 매번 한다. 공기 주입 청진만으로는 부족하며 흡인물 확인·X선이 기준이다. 위치가 틀리면 폐로 들어간다.",
    sources: ["khna-guideline"],
  },
  {
    id: "iv-line",
    ko: "정맥주사",
    en: "intravenous",
    abbr: "IV",
    aliases: ["아이브이", "정맥주입", "라인", "수액라인"],
    category: "device",
    definition: "말초정맥에 카테터를 유치해 약물·수액을 주입하는 경로.",
    pitfall:
      "발적·부종·통증·주입저항은 침윤/정맥염 신호다. 확인 즉시 중단하고 제거한 뒤 보고·기록한다.",
    sources: ["khna-guideline"],
  },
  {
    id: "central-line",
    ko: "중심정맥관",
    en: "central venous catheter",
    abbr: "CVC",
    aliases: ["씨라인", "중심정맥", "씨브이씨", "센트럴라인"],
    category: "device",
    definition: "대정맥까지 끝이 도달하는 카테터. 고농도 약물·TPN 투여와 중심정맥압 측정에 쓴다.",
    pitfall: "혈류감염 위험이 크다. 삽입부 드레싱 상태와 필요성 재평가를 매 근무 확인한다.",
    sources: ["kdca-hai", "khna-guideline"],
  },
  {
    id: "picc",
    ko: "말초삽입중심정맥관",
    en: "peripherally inserted central catheter",
    abbr: "PICC",
    aliases: ["픽", "피아이씨씨", "픽라인"],
    category: "device",
    definition: "팔의 말초정맥으로 넣어 끝이 중심정맥에 놓이는 카테터. 장기 정맥요법에 쓴다.",
    pitfall: "삽입측 팔에서 혈압 측정과 채혈은 하지 않는다. 외부 노출 길이를 매번 확인해 이탈을 잡는다.",
    sources: ["khna-guideline"],
  },
  {
    id: "arterial-line",
    ko: "동맥관",
    en: "arterial line",
    abbr: "A-line",
    aliases: ["에이라인", "동맥라인", "아트라인"],
    category: "device",
    definition: "동맥에 유치해 혈압을 연속 측정하고 동맥혈을 채취하는 라인.",
    pitfall: "빠지면 대량 출혈로 직결된다. 연결부 고정과 순환 상태(색·온도·감각)를 자주 확인한다.",
  },
  {
    id: "chest-tube",
    ko: "흉관",
    en: "chest tube",
    aliases: ["체스트튜브", "흉관배액", "흉강삽관"],
    category: "device",
    definition: "흉막강의 공기나 액체를 배출시켜 폐 확장을 돕는 관.",
    pitfall: "배액병은 항상 흉부보다 낮게 두고, 관을 잠그거나 들어올리지 않는다. 갑작스러운 기포 증가는 공기누출 신호다.",
  },
  {
    id: "tracheostomy",
    ko: "기관절개관",
    en: "tracheostomy tube",
    aliases: ["트라키", "기관절개", "티캐뉼라"],
    category: "device",
    definition: "목 앞을 절개해 기도로 직접 넣은 인공기도.",
    pitfall: "우발적 발관은 응급이다. 같은 크기와 한 단계 작은 예비 캐뉼라를 침상 옆에 항상 둔다.",
  },
  {
    id: "three-way",
    ko: "삼방활전",
    en: "three-way stopcock",
    aliases: ["쓰리웨이", "삼방"],
    category: "device",
    definition: "수액 라인 중간에 달아 약물을 추가 주입할 수 있게 하는 삼방향 밸브.",
    pitfall: "방향 표시를 확인하지 않고 돌리면 수액이 잠기거나 역류한다. 개방구는 반드시 캡을 씌운다.",
  },
  {
    id: "infusion-pump",
    ko: "주입펌프",
    en: "infusion pump",
    aliases: ["인퓨전펌프", "인퓨전", "펌프", "시린지펌프"],
    category: "device",
    definition: "정해진 속도로 수액·약물을 주입하는 장비.",
    pitfall:
      "고위험약물은 설정 속도를 두 사람이 확인한다(더블체크). 알람을 껐다가 그대로 두는 것이 사고의 전형적 경로다.",
    sources: ["koiha"],
  },
  {
    id: "oxygen-device",
    ko: "산소요법 기구",
    en: "oxygen delivery device",
    aliases: ["나잘프롱", "네이잘프롱", "벤츄리", "벤추리마스크", "하이플로우", "산소마스크", "오투"],
    category: "device",
    definition:
      "비강캐뉼라(nasal prong), 단순마스크, 벤츄리마스크, 비재호흡마스크, 고유량비강캐뉼라 등 산소 투여 기구.",
    pitfall: "기구마다 전달 가능한 산소농도 범위가 다르다. 처방된 농도가 나오지 않는 기구를 쓰면 처방을 어긴 것이다.",
  },
  {
    id: "ambu-bag",
    ko: "수동식 인공호흡기",
    en: "bag valve mask",
    aliases: ["앰부", "앰부백", "백밸브마스크"],
    category: "device",
    definition: "손으로 짜서 환기를 제공하는 백-밸브-마스크.",
    pitfall: "산소 연결과 저장백 부풀림을 확인하지 않으면 실내공기만 넣는 셈이 된다. 침상 옆 비치 여부를 근무 시작 때 확인한다.",
  },
  {
    id: "hemovac",
    ko: "헤모박",
    en: "Hemovac drain",
    aliases: ["헤모박", "헤모백", "배액관"],
    category: "device",
    definition: "수술 부위의 삼출물을 음압으로 모으는 폐쇄식 배액 장치.",
    pitfall: "비운 뒤 다시 압축(음압 재형성)을 하지 않으면 배액이 멈춘다. 배액량과 색을 시간대별로 기록한다.",
  },

  // ── 검사 ────────────────────────────────────────────────
  {
    id: "cbc",
    ko: "일반혈액검사",
    en: "complete blood count",
    abbr: "CBC",
    aliases: ["씨비씨", "시비시", "일반혈액"],
    category: "lab",
    definition: "백혈구·적혈구·혈색소·혈소판 등을 측정하는 기본 혈액검사.",
    pitfall: "호중구감소 환자는 발열 자체가 응급이다(호중구감소성 발열). 수치를 보면 감염 예방 조치를 같이 떠올린다.",
  },
  {
    id: "abga",
    ko: "동맥혈가스분석",
    en: "arterial blood gas analysis",
    abbr: "ABGA",
    aliases: ["에이비지에이", "가스분석", "에이비지"],
    category: "lab",
    definition: "동맥혈의 pH·PaCO2·PaO2·HCO3를 측정해 산-염기 및 산소화 상태를 보는 검사.",
    pitfall: "채혈 후 공기 제거와 즉시 이송이 필수. 지연되면 값이 변한다. 채혈 부위는 5분 이상 압박한다.",
  },
  {
    id: "culture-sensitivity",
    ko: "배양 및 항생제감수성검사",
    en: "culture and sensitivity",
    abbr: "C/S",
    aliases: ["컬쳐", "컬처", "씨에스", "배양검사", "혈액배양", "블러드컬쳐"],
    category: "lab",
    definition: "검체에서 균을 배양하고 어떤 항생제가 듣는지 확인하는 검사.",
    pitfall: "항생제 투여 '전'에 채취해야 의미가 있다. 혈액배양은 서로 다른 부위에서 2세트가 원칙이다.",
    sources: ["kdca-hai"],
  },
  {
    id: "electrolyte",
    ko: "전해질검사",
    en: "electrolyte panel",
    aliases: ["일렉트로라이트", "전해질", "이온검사"],
    category: "lab",
    definition: "나트륨·칼륨·염소·칼슘 등 혈중 전해질 농도 검사.",
    pitfall: "칼륨 이상은 치명적 부정맥으로 이어진다. 결과가 심하게 벗어나면 즉시 노티 대상이다.",
  },
  {
    id: "pt-inr",
    ko: "프로트롬빈시간/INR",
    en: "prothrombin time / INR",
    abbr: "PT/INR",
    aliases: ["피티아이엔알", "아이엔알", "피티"],
    category: "lab",
    definition: "혈액 응고 시간을 나타내는 검사. 와파린 용량 조절의 기준.",
    pitfall: "INR이 높으면 출혈 위험이 크다. 침습적 처치 전 확인하고, 압박 시간을 늘린다.",
  },

  // ── 상태 / 응급 ──────────────────────────────────────────
  {
    id: "cardiac-arrest",
    ko: "심정지",
    en: "cardiac arrest",
    aliases: ["어레스트", "카디악어레스트", "심정지발생"],
    category: "emergency",
    definition: "심장의 효과적 박출이 멈춘 상태. 즉시 심폐소생술 대상.",
    pitfall: "반응·호흡 확인은 10초 이내. 발견 즉시 도움 요청과 가슴압박이 먼저다.",
    sources: ["kacpr"],
  },
  {
    id: "cpr",
    ko: "심폐소생술",
    en: "cardiopulmonary resuscitation",
    abbr: "CPR",
    aliases: ["씨피알", "시피알", "심폐소생"],
    category: "emergency",
    definition: "가슴압박과 인공호흡으로 순환과 호흡을 대신하는 응급처치.",
    pitfall: "압박 깊이 약 5cm, 속도 분당 100~120회, 완전한 이완. 교대는 2분마다.",
    sources: ["kacpr"],
  },
  {
    id: "dnr",
    ko: "심폐소생술금지",
    en: "do not resuscitate / do not attempt resuscitation",
    abbr: "DNR",
    aliases: ["디엔알", "디엔에이알", "연명의료중단"],
    category: "emergency",
    definition:
      "심정지 시 심폐소생술을 시행하지 않기로 한 결정. 국내에서는 연명의료결정법에 따른 문서 절차를 따른다.",
    pitfall:
      "DNR은 '아무것도 하지 않는다'가 아니다. 통증조절·산소·체위 같은 다른 간호는 그대로 유지된다. 서류 확인 없이 구두로만 처리하면 안 된다.",
    sources: ["law-go-kr"],
  },
  {
    id: "code-blue",
    ko: "코드블루",
    en: "code blue",
    aliases: ["코드블루", "블루콜"],
    category: "emergency",
    definition: "원내 심정지 발생을 알리는 비상 호출 코드.",
    pitfall: "누가 방송하고 누가 압박하고 누가 기록하는지 역할이 즉시 나뉘어야 한다. 병동별 지정 위치를 미리 외워둔다.",
  },
  {
    id: "rrt",
    ko: "신속대응팀",
    en: "rapid response team",
    abbr: "RRT",
    aliases: ["알알티", "신속대응", "래피드리스폰스"],
    category: "emergency",
    definition: "심정지 이전 단계의 악화 징후를 보이는 환자에게 조기 개입하는 원내 전담팀.",
    pitfall: "'아직 어레스트는 아니니까'가 가장 위험한 판단이다. 호출 기준에 걸리면 주저 없이 부른다.",
    sources: ["koiha"],
  },
  {
    id: "anaphylaxis",
    ko: "아나필락시스",
    en: "anaphylaxis",
    aliases: ["아나필락시스", "아나필락스", "과민반응"],
    category: "emergency",
    definition: "급격히 진행하는 전신 알레르기 반응. 기도부종·저혈압·쇼크로 진행할 수 있다.",
    pitfall: "의심되면 투여를 즉시 중단하고 도움을 요청한다. 에피네프린 근육주사가 1차 치료다.",
  },
  {
    id: "fall-down",
    ko: "낙상",
    en: "fall",
    aliases: ["폴다운", "폴", "낙상발생", "떨어짐"],
    category: "condition",
    definition: "환자가 의도치 않게 바닥이나 낮은 곳으로 넘어진 사건.",
    pitfall:
      "발견 즉시 바로 일으키지 말고 의식·통증·손상 여부부터 사정한다. 환자안전 보고는 처벌이 아니라 재발 방지 절차다.",
    sources: ["koiha", "kops"],
  },
  {
    id: "expire",
    ko: "사망",
    en: "expire",
    aliases: ["익스파이어", "임종"],
    category: "condition",
    definition: "환자의 사망. 기록에는 사망 시각과 확인 의사를 남긴다.",
    formal: "사망",
    pitfall: "사후 처치와 서류(사망진단서·시신 인계)는 병원 절차가 정해져 있다. 유가족 응대 방식도 함께 인계받는다.",
  },
  {
    id: "aspiration",
    ko: "흡인(사레)",
    en: "aspiration",
    aliases: ["애스피레이션", "흡인성", "사레", "기도흡인"],
    category: "condition",
    definition: "음식물·분비물·위 내용물이 기도로 들어가는 것. 흡인성 폐렴의 원인.",
    pitfall: "경관영양 중에는 상체를 30~45도 올리고 주입 후에도 일정 시간 유지한다. 기침·산소포화도 저하는 경고 신호다.",
    sources: ["khna-guideline"],
  },
  {
    id: "delirium",
    ko: "섬망",
    en: "delirium",
    aliases: ["딜리리움", "섬망증상"],
    category: "condition",
    definition: "갑작스럽게 시작되고 하루 중에도 변동하는 의식·주의력 장애.",
    pitfall:
      "치매와 달리 급성이고 원인이 있다. '원래 그런 분'으로 넘기지 말고 감염·저산소·약물·통증·탈수를 찾아본다.",
  },
  {
    id: "pressure-injury",
    ko: "욕창",
    en: "pressure injury",
    aliases: ["프레셔소어", "욕창발생", "베드소어", "소어"],
    category: "condition",
    definition: "지속적인 압력으로 피부와 하부조직이 손상된 상태. 단계(1~4, 심부조직손상, 미분류)로 기술한다.",
    pitfall: "발적이 눌러도 사라지지 않으면 이미 1단계다. 입원 시 전신 피부 상태를 기록해야 원내 발생 여부를 가릴 수 있다.",
    sources: ["khna-guideline"],
  },
];
