import type { LexiconEntry } from "./types.js";

/**
 * 투약 관련 용어.
 *
 * 신규간호사 사고의 다수가 투약에서 난다. 그래서 이 카테고리는 정의보다
 * `pitfall`(놓치는 지점)에 무게를 실었다. 학습카드에서도 pitfall을 별도 카드로 뽑는다.
 */
export const MEDICATION_TERMS: LexiconEntry[] = [
  {
    id: "prn",
    ko: "필요시 투여",
    en: "pro re nata",
    abbr: "PRN",
    aliases: ["피알엔", "피알엔오더", "필요시"],
    category: "medication",
    definition: "정해진 조건이 충족될 때만 투여하는 처방.",
    pitfall:
      "'필요시'의 조건(무엇이 몇 이상일 때)과 최소 투여 간격, 1일 최대 횟수가 처방에 있다. 투여 사유와 효과 재평가를 반드시 기록한다.",
  },
  {
    id: "stat",
    ko: "즉시 투여",
    en: "statim",
    abbr: "STAT",
    aliases: ["스탯", "즉시처방"],
    category: "medication",
    definition: "지체 없이 즉시 시행해야 하는 처방.",
    pitfall: "STAT은 '이번 라운드에 같이'가 아니다. 다른 일을 멈추고 먼저 한다. 시행 시각을 분 단위로 기록한다.",
  },
  {
    id: "npo",
    ko: "금식",
    en: "nil per os",
    abbr: "NPO",
    aliases: ["엔피오", "금식중", "엔피오유지"],
    category: "medication",
    definition: "입으로 아무것도 주지 않는 상태. 수술·검사·흡인위험 등에서 적용한다.",
    pitfall:
      "NPO 중에도 투여해야 하는 약(항경련제·심장약 등)이 있다. 일괄 중단하지 말고 처방을 확인한다. 시작 시각과 사유를 침상과 기록 양쪽에 남긴다.",
  },
  {
    id: "po",
    ko: "경구 투여",
    en: "per os",
    abbr: "PO",
    aliases: ["피오", "경구", "먹는약"],
    category: "medication",
    definition: "입으로 삼켜 투여하는 경로.",
    pitfall: "삼킴장애가 있으면 경로 자체를 재검토해야 한다. 서방정·장용정은 부수거나 갈면 안 된다.",
  },
  {
    id: "im",
    ko: "근육주사",
    en: "intramuscular",
    abbr: "IM",
    aliases: ["아이엠", "근주", "근육주사"],
    category: "medication",
    definition: "근육층에 약물을 주사하는 경로.",
    pitfall: "성인 표준 부위는 배둔근(ventrogluteal)과 삼각근. 주사 전 흡인 여부는 약물·부위 지침을 따른다.",
  },
  {
    id: "sc",
    ko: "피하주사",
    en: "subcutaneous",
    abbr: "SC",
    aliases: ["에스씨", "에스큐", "피하주사", "피하"],
    category: "medication",
    definition: "피하지방층에 주사하는 경로. 인슐린·헤파린 등에 쓴다.",
    pitfall: "같은 자리에 반복하면 지방위축·경결이 생겨 흡수가 달라진다. 부위를 순환시키고 기록한다.",
  },
  {
    id: "iv-side",
    ko: "정맥 측관 주입",
    en: "IV side injection",
    aliases: ["사이드", "아이브이사이드", "측관", "사이드로주다"],
    category: "medication",
    definition: "이미 유지 중인 수액 라인의 삼방활전을 통해 약물을 주입하는 방식.",
    informal: true,
    formal: "정맥 측관 주입",
    pitfall: "함께 흐르는 수액과의 배합금기를 먼저 확인한다. 침전이 생기면 라인이 막히고 색전 위험이 생긴다.",
  },
  {
    id: "iv-mix",
    ko: "수액 혼합",
    en: "IV admixture",
    aliases: ["믹스", "믹스하다", "수액믹스"],
    category: "medication",
    definition: "수액백에 약물을 섞어 주입 가능한 형태로 만드는 조제 행위.",
    informal: true,
    formal: "정맥주입용 약물 혼합",
    pitfall: "혼합 시각과 유효시간을 라벨에 적는다. 조제 후 색 변화·침전이 보이면 사용하지 않는다.",
    sources: ["khna-guideline"],
  },
  {
    id: "tpn",
    ko: "완전비경구영양",
    en: "total parenteral nutrition",
    abbr: "TPN",
    aliases: ["티피엔", "티피앤", "고영양수액"],
    category: "medication",
    definition: "소화관을 거치지 않고 정맥으로 필요한 영양소 전부를 공급하는 요법.",
    pitfall:
      "중심정맥으로 투여하며 감염·고혈당 위험이 크다. 갑자기 중단하면 저혈당이 올 수 있으므로 임의 중단하지 않는다.",
    sources: ["khna-guideline"],
  },
  {
    id: "heparin-lock",
    ko: "헤파린 잠금",
    en: "heparin lock",
    aliases: ["헤파린락", "헤파린록", "헤파린잠금", "락걸다"],
    category: "medication",
    definition: "카테터 내강을 헤파린 용액으로 채워 막힘을 예방하는 처치.",
    pitfall: "기관마다 농도와 적응증이 다르다. 생리식염수 잠금으로 대체하는 곳도 많으니 병원 지침을 확인한다.",
  },
  {
    id: "high-alert-medication",
    ko: "고위험약물",
    en: "high-alert medication",
    aliases: ["하이알럿", "고위험의약품", "고위험약"],
    category: "medication",
    definition:
      "투약 오류 시 환자에게 치명적 위해를 줄 수 있는 약물군. 고농도 전해질, 인슐린, 항응고제, 마약류, 항암제 등.",
    pitfall:
      "별도 보관·표시·독립 이중확인이 원칙이다. 특히 고농도 KCl은 절대 원액 정맥주사 금지 — 반드시 희석한다.",
    sources: ["koiha", "kops"],
  },
  {
    id: "double-check",
    ko: "이중확인",
    en: "independent double check",
    aliases: ["더블체크", "이중확인", "더블첵"],
    category: "medication",
    definition: "두 사람이 각자 독립적으로 약물·용량·경로·환자를 확인하는 절차.",
    pitfall:
      "옆에서 '맞죠?' 하고 고개만 끄덕이는 건 이중확인이 아니다. 서로의 결론을 보지 않은 상태에서 각자 확인해야 의미가 있다.",
    sources: ["koiha"],
  },
  {
    id: "five-rights",
    ko: "투약의 기본 원칙",
    en: "rights of medication administration",
    aliases: ["파이브라이트", "투약원칙", "5원칙", "투약5원칙"],
    category: "medication",
    definition:
      "정확한 대상자·약물·용량·경로·시간. 여기에 정확한 기록, 정확한 사유, 대상자의 알 권리와 거부권을 더해 확장해 쓴다.",
    pitfall: "'정확한 대상자'는 이름 부르기가 아니라 개방형 질문과 팔찌 등 두 가지 지표 확인이다.",
    sources: ["koiha"],
  },
  {
    id: "patient-identification",
    ko: "환자확인",
    en: "patient identification",
    aliases: ["환자확인", "아이디확인", "팔찌확인"],
    category: "medication",
    definition: "처치·투약·검체 채취 전 두 가지 이상의 지표로 대상자를 확인하는 절차.",
    pitfall: "병실 번호와 침상 번호는 지표로 쓸 수 없다. 환자가 스스로 말하게 하는 개방형 질문이 기본이다.",
    sources: ["koiha"],
  },
  {
    id: "hold-medication",
    ko: "투약 보류",
    en: "hold",
    aliases: ["홀딩", "홀드", "보류", "홀딩하다"],
    category: "medication",
    definition: "특정 조건 때문에 예정된 약을 일시적으로 주지 않는 것.",
    informal: true,
    formal: "투약 보류",
    pitfall: "보류는 반드시 사유·시각·보고 여부를 기록한다. 기록 없는 보류는 누락과 구분되지 않는다.",
  },
  {
    id: "skip-medication",
    ko: "투약 누락",
    en: "omitted dose",
    aliases: ["스킵", "스킵됨", "누락", "빠뜨림"],
    category: "medication",
    definition: "예정된 투약이 시행되지 않은 것.",
    informal: true,
    formal: "투약 누락",
    pitfall: "숨기면 다음 근무자가 이중으로 주거나 계속 빠뜨린다. 발견 즉시 보고하고 기록하는 것이 환자를 지키는 쪽이다.",
    sources: ["kops"],
  },
  {
    id: "insulin-cover",
    ko: "인슐린 추가 투여",
    en: "insulin sliding scale coverage",
    aliases: ["커버", "인슐린커버", "슬라이딩스케일", "커버쳤다"],
    category: "medication",
    definition: "혈당 수치에 따라 정해진 표대로 속효성 인슐린을 추가 투여하는 것.",
    informal: true,
    formal: "혈당에 따른 인슐린 추가 투여",
    pitfall: "식사 여부와 혈당 측정 시각이 함께 맞아야 한다. 식사를 못 한 환자에게 표대로 주면 저혈당이 온다.",
  },
  {
    id: "narcotic-count",
    ko: "마약류 재고 확인",
    en: "narcotic count",
    aliases: ["마약체크", "마약카운트", "마약인계"],
    category: "medication",
    definition: "근무 교대 시 마약류 수량과 기록을 두 사람이 대조 확인하는 절차.",
    pitfall: "잔량 폐기도 두 사람이 함께 확인하고 서명한다. 마약류관리법상 기록 의무가 있으므로 임의 처리 불가.",
    sources: ["law-go-kr", "mfds-drug"],
  },
  {
    id: "adverse-drug-reaction",
    ko: "약물유해반응",
    en: "adverse drug reaction",
    abbr: "ADR",
    aliases: ["에이디알", "부작용", "약물부작용", "유해반응"],
    category: "medication",
    definition: "정상 용법·용량에서 발생한 유해하고 의도되지 않은 약물 반응.",
    pitfall: "발생하면 환자 기록에 남겨 다음 처방 때 재노출을 막아야 한다. 병원 보고 체계와 식약처 보고 대상이 될 수 있다.",
    sources: ["mfds-drug"],
  },
  {
    id: "dur",
    ko: "의약품안전사용서비스",
    en: "Drug Utilization Review",
    abbr: "DUR",
    aliases: ["디유알", "듀알", "디유아르"],
    category: "medication",
    definition: "처방·조제 시 병용금기, 연령금기, 임부금기 등을 실시간으로 점검해주는 국가 시스템.",
    pitfall: "DUR 경고가 뜨면 그냥 넘기지 말고 사유를 확인한다. 팝업을 습관적으로 닫는 것이 위험 신호다.",
    sources: ["mfds-drug"],
  },
];
